version: '3.1'

services:
  mongo:
    container_name: mongo
    build: ./
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # [ REMOVED MONGO-EXPRESS FOR PRISMA STUDIO ]
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo

volumes:
  mongo: